# Managed by global-nix. Determinate Nix includes this from /etc/nix/nix.conf.
extra-substituters = https://jessfraz-global-nix.cachix.org
extra-trusted-public-keys = jessfraz-global-nix.cachix.org-1:YfZ5ZSDbd3C0ROthje1wND5ps5XameBUZ2ImUokMNy8=
