name: Test Nix Flake
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: "extra-experimental-features = pipe-operators"
      - run: nix flake check
  aarch64-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: "extra-experimental-features = pipe-operators"
      - run: nix flake check
